BTL_HTTT/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("homepage.urls")),
    path('admin/', admin.site.urls),
]

homepage/urls.py
from django.urls import path
from . import views
app_name = "homepage"
urlpatterns = [
    path('', views.TrangChu, name = "trangchu"),
    path("result/", views.KetQua, name = 'ketqua' )
]

homepage/models.py
from django.db import models

# Create your models here.
class Benh(models.Model):
    ten_benh = models.CharField(max_length=200)
    kh = models.CharField(max_length=50)
    nguyen_nhan = models.TextField(blank=True)
    dieu_tri = models.TextField(blank=True)

    def __str__(self):
        return self.ten_benh

class TrieuChung(models.Model):
    benh = models.ForeignKey(Benh, on_delete= models.CASCADE)
    ten = models.CharField(max_length=200)
    ki_hieu = models.CharField(max_length=50)
    trongso = models.IntegerField(default=1)
    gia_tri = models.FloatField(default=0)
    def __str__(self):
        return self.ten

homepage/views.py
from django.shortcuts import render
from django.views import View
from django.http import request
from .models import Benh, TrieuChung
from .ultils import cbr
# Create your views here.

def TrangChu(request):
    benh = Benh.objects.all()[0];
    list_tc = benh.trieuchung_set.all().order_by("ki_hieu")
    context = {"list_tc": list_tc}
    return render(request, "TrangChu.html", context)

def KetQua(request):
    vote = {
    'p01' : request.POST['p01'],
    'p02' : request.POST['p02'],
    'p03' : request.POST['p03'],
    'p04' : request.POST['p04'],
    'p05' : request.POST['p05'],
    'p06' : request.POST['p06'],
    'p07' : request.POST['p07'],
    'p08' : request.POST['p08'],
    'p09' : request.POST['p09'],
    'p10' : request.POST['p10'],
    'p11' : request.POST['p11'],
    'p12' : request.POST['p12'],
    'p13' : request.POST['p13'],
    'p14' : request.POST['p14'],
    'p15' : request.POST['p15'],
    'p16' : request.POST['p16'],
    'p17' : request.POST['p17'],
    'p18' : request.POST['p18'],
    'p19' : request.POST['p19'],
    'p20' : request.POST['p20'],
    'p21' : request.POST['p21'],
    'p22' : request.POST['p22'],
    'p23' : request.POST['p23'],
    'p24' : request.POST['p24']
    }
    list_kq = []
    for value in vote.values():
        list_kq.append(float(value))
    index = cbr(list_kq)
    context = {"result": Benh.objects.get(pk = index)}
    return render(request, "KetQua.html", context)

homepage/templates/KetQua.html
{% extends "base.html" %}
{% block static_extension %}
    <title>Kết quả tư vấn</title>
    <link rel="stylesheet" href="../static/css/ketqua.css">
{% endblock static_extension %}
<body>
    {% block content %}
        <h3>Kết quả</h3>
       <div class="table">
        <table id="result">
          <tr>
            <th>Tên bệnh</th>
            <th>Nguyên nhân</th>
            <th>Lời khuyên</th>
          </tr>
          <tr>
            <td>{{ result.ten_benh }}</td>
            <td>{{ result.nguyen_nhan}}</td>
            <td>{{ result.dieu_tri }}</td>
          </tr>
       </table>
       </div>
    {% endblock content %}
</body>

homepage/templates/TrangChu.html
{% extends "base.html" %}
{% block static_extension %}
    <title>Hệ thống tư vấn chuẩn đoán bệnh xương khớp</title>
    <link rel="stylesheet" href="../static/css/trangchu.css">
{% endblock static_extension %}
<body>
    {% block content %}
    {% if list_tc %}
        <form action="{% url "homepage:ketqua" %}" method="post">
        {% csrf_token %}
            <div class="the-form">
                {% for tc in list_tc %}
                <div class="vote">
                    <p class="the_label">{{ tc.ten }}</p>
                    <div class="choice">
                        <input type="radio" name="{{ tc.ki_hieu }}" value="0" checked id="khong{{ tc.ki_hieu }}"> <label for="khong{{ tc.ki_hieu }}">Không</label>
                        <input type="radio" name="{{ tc.ki_hieu }}" value="0.2" id="nhe{{ tc.ki_hieu }}"> <label for="nhe{{ tc.ki_hieu }}">Nhẹ</label>
                        <input type="radio" name="{{ tc.ki_hieu }}" value="0.5" id="vua{{ tc.ki_hieu }}"> <label for="vua{{ tc.ki_hieu }}">Vừa</label>
                        <input type="radio" name="{{ tc.ki_hieu }}" value="0.8" id="nang{{ tc.ki_hieu }}"> <label for="nang{{ tc.ki_hieu }}">Nặng</label>
                    </div>
                </div>
            {% endfor %}
            </div>
        <div id="btn"><input type="submit" value="Submit"  class="button-5"></div>
        </form>
    {% else %}
        <h3>Chưa có dữ liệu</h3>
    {% endif %}
    {% endblock content %}
</body>

homepage/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    {% load static %}
    <link rel="stylesheet" href="../static/css/header.css">

    {% block static_extension %}
        <title>Hệ thống tư vấn chuẩn đoán bệnh xương khớp</title>

    {% endblock static_extension %}
</head>
<body>
    {% block header %}
        <header>
            <p class="image"><a href="{% url "homepage:trangchu" %}"><img src="../static/logo/Logo_PTIT_University.png"></a></p>
            <p class="title">Hệ thống tư vấn chuẩn đoán bệnh về xương khớp</p>
        </header>
    {% endblock header %}
    <main>
        {% block content %}
        {% endblock content %}
    </main>
</body>
</html>